// @generated by pi-protocol generate; DO NOT EDIT.
// contract-digest: sha256:832f1bc01883c0f40658db8db6733b46ede715698db56de786dde92bc53c614c
import type { ProtocolAgentExecutor, ProtocolHandler } from "@kybernetria/pi-protocol/core";

export const PROTOCOL_NODE_ID = "pi_todo" as const;
export const PROTOCOL_TARGETS = {
  list: "pi_todo.list",
  get: "pi_todo.get",
  create: "pi_todo.create",
  update: "pi_todo.update",
  delete: "pi_todo.delete",
  assign: "pi_todo.assign",
} as const;

export type ProtocolProvideName = "list" | "get" | "create" | "update" | "delete" | "assign";
export type ProtocolBinding = ProtocolHandler | ProtocolAgentExecutor;
export type ProtocolBindings = {
  "list": ProtocolBinding;
  "get": ProtocolBinding;
  "create": ProtocolBinding;
  "update": ProtocolBinding;
  "delete": ProtocolBinding;
  "assign": ProtocolBinding;
};

export type ListInput = { include_closed?: boolean; };
export type ListOutput = { assigned?: readonly { assigned_to_session?: string; created_at?: string; id?: string; parent_id?: string; status?: string; tags?: readonly string[]; title?: string; }[]; closed?: readonly { assigned_to_session?: string; created_at?: string; id?: string; parent_id?: string; status?: string; tags?: readonly string[]; title?: string; }[]; error?: string; open?: readonly { assigned_to_session?: string; created_at?: string; id?: string; parent_id?: string; status?: string; tags?: readonly string[]; title?: string; }[]; };
export type GetInput = { id: string; };
export type GetOutput = { assigned_to_session?: string; body?: string; created_at?: string; error?: string; id?: string; parent_id?: string; status?: string; tags?: readonly string[]; title?: string; };
export type CreateInput = { body?: string; parent_id?: string | null; status?: string; tags?: readonly string[]; title: string; };
export type CreateOutput = { assigned_to_session?: string; body?: string; created_at?: string; error?: string; id?: string; parent_id?: string; status?: string; tags?: readonly string[]; title?: string; };
export type UpdateInput = { body?: string; body_mode?: "replace" | "append"; id: string; parent_id?: string | null; status?: string; tags?: readonly string[]; title?: string; };
export type UpdateOutput = { assigned_to_session?: string; body?: string; created_at?: string; error?: string; id?: string; parent_id?: string; status?: string; tags?: readonly string[]; title?: string; };
export type DeleteInput = { id: string; };
export type DeleteOutput = { assigned_to_session?: string; body?: string; created_at?: string; error?: string; id?: string; parent_id?: string; status?: string; tags?: readonly string[]; title?: string; };
export type AssignInput = { action: "claim" | "release"; force?: boolean; id: string; };
export type AssignOutput = { assigned_to_session?: string; body?: string; created_at?: string; error?: string; id?: string; parent_id?: string; status?: string; tags?: readonly string[]; title?: string; };
